publish_mode: editorial_workflow
backend:
  name: github
  repo: BFM-Community/www.bfm-community.eu
  branch: master
  base_url: https://1c4bi963n0.execute-api.eu-central-1.amazonaws.com
  auth_endpoint: /prod/auth
  site_domain: bfm-community.github.io

site_id: www.bfm-community.eu

media_folder: "media/uploads"
public_folder: "www.bfm-community.eu/media/uploads"

collections:
  - name: "pages"
    label: "Pages" # Used in the UI
    folder: "/" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "string", default: "page"}
      - {label: "Image", name: "img", widget: "image", required: false}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Id", name: "id", widget: "string"}
      - {label: "Description", name: "description", widget: "string", required: false}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "home-sections" # Used in routes, e.g., /admin/collections/blog
    label: "Home Sections" # Used in the UI
    folder: "_posts/" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "default"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Image", name: "img", widget: "image", required: false}
      - {label: "Sitemap", name: "sitemap", widget: "boolean"}
      - {label: "Category", name: "category", widget: "string"}
      - {label: "Section", name: "section", widget: "string"}
      - {label: "Description", name: "description", widget: "string", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
